name: main

on:
  push: 
    branches: ["main"]
  pull_request: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置 Chromium
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          chrome-version: stable

      - run: npm install & build
      
      - name: 生成网页快照
        id: snapshot_step
        uses: ./
        with:
          website: 'https://www.github.com'
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          
      - name: 上传截图结果
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: website-snapshots
          path: snapshots/*.png
          retention-days: 5
